import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ThemeEffect } from "@/components/ThemeEffect";
import { HeaderClient } from "@/components/HeaderClient";
import { ClientProviders } from "@/components/ClientProviders";
import { AppFooter } from "@/components/AppFooter";

/* The canonical origin. Without an explicit `metadataBase`, Next derives
   absolute URLs (og:image, share cards) from whichever host served the request,
   so the apex and the www alias each advertised themselves as canonical and
   search engines saw two different builds of the same site. Pin it here and
   both hosts emit identical, apex-based URLs. */
const SITE_ORIGIN = "https://godoor.site";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_ORIGIN),
  title: "GoDoor — Delivering Possibilities",
  description:
    "Hyper-local delivery platform for Uganda. Food, groceries, pharmacy & packages — delivered to your door. Pay with GoDoor Wallet.",
  // Official brand artwork, generated by scripts/build-brand-assets.mjs.
  // `manifest` was never wired up before, so the PWA manifest (and the icons
  // it references) was never actually being requested by the installed app.
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/brand/favicon-32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/brand/apple-touch-icon.png", sizes: "180x180" }],
  },
  openGraph: {
    title: "GoDoor — Your City. Your Door.",
    description: "Order food, groceries, pharmacy & packages. Delivered to your door in minutes. Pay with GoDoor Wallet.",
    siteName: "GoDoor",
    type: "website",
    url: SITE_ORIGIN,
  },
  twitter: {
    card: "summary_large_image",
    title: "GoDoor — Delivering Possibilities",
    description: "Food, groceries, pharmacy & packages delivered to your door. Pay with GoDoor Wallet.",
  },
};

/**
 * Pre-paint theme resolution.
 *
 * `useThemeEffect` can only run after hydration, so without this the server
 * markup (`class="light"`) would paint first and dark-mode users would get a
 * white flash on every page load. This reads the same persisted key zustand
 * uses and applies the class before the browser paints any body content.
 *
 * Kept in sync with `src/lib/theme-store.ts` (storage key + light/dark tokens).
 */
const themePreloadScript = `
(function () {
  try {
    var raw = localStorage.getItem("godoor-theme-v5-white");
    var stored = raw ? JSON.parse(raw) : null;
    var theme = (stored && stored.state && stored.state.theme) || "light";
    var resolved = theme === "system"
      ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
      : theme;
    var root = document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(resolved);
    var meta = document.querySelector('meta[name="theme-color"]');
    if (meta) meta.setAttribute("content", resolved === "dark" ? "#060B18" : "#F8F7FC");
  } catch (e) {}
})();
`.trim();

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#F8F7FC",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // The script rewrites the class on <html>, so React must accept the DOM as-is.
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themePreloadScript }} />
      </head>
      <body className="font-sans antialiased">
        <ThemeEffect />
        <HeaderClient />
        <ClientProviders>
          <main className="min-h-0">{children}</main>
        </ClientProviders>
        <AppFooter />
      </body>
    </html>
  );
}
